### ISSUE TITLE
[BUG] ERROR: Could not pass event AsyncPlayerTreeFallEvent to SmoothTimber v1.16.5

### ISSUE THREAD

**Issue by ldiego2601** [SourceWriters/SmoothTimber#14] opened 2021-07-04 20:55 UTC
**Describe the bug**
I started using smoothtimber 1.16.5 in my papermv 1.16.5 server and I'm getting the following error:
[14:51:03 ERROR]: Could not pass event AsyncPlayerTreeFallEvent to SmoothTimber v1.16.5
java.lang.NoSuchMethodError: com.gamingmesh.jobs.container.Job.getJobKeyName()Ljava/lang/String;
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.jobsreborn.JobsRebornFallListener.onFallEvent(JobsRebornFallListener.java:31) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor265.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-779]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-779]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-779]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-779]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerFallEvent(SmoothTimber.java:65) ~[?:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1$1.lambda$run$0(BlockBreakListener.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-779]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-779]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-779]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_291]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**To Reproduce**
1. Go to any tree and chop it down with an axe.

**Expected behavior**
For the tree to be smoothly chopped and fall into the ground. Your plugin animation does work but the error appears in the server log.

**Media**
N/A

**Server:**

 - Software: PaperMC
 - Server Version: 1.16.5 #779
 - Plugin Version: 1.16.5
 - Java Version: 1.8.0u291

**Additional context**
Problem seem to be the interaction with the plugin:
- Jobs Reborn v5.0.0.1

**Comment by YellowPhoenix18** [comment] 2021-07-04 21:01
How should we reproduce an error without informations? Either you add Infos like a log etc. here or we can't help

**Comment by ldiego2601** [comment] 2021-07-04 21:20
> 
> 
> How should we reproduce an error without informations? Either you add Infos like a log etc. here or we can't help

I just did. Can we re-open this ticket?

**Comment by Lauriichan** [comment] 2021-07-09 08:45
Duplicate of #12

**Closed as completed by Lauriichan** 2021-07-09 08:45 UTC
Labels: Bug, Duplicate
