### ISSUE TITLE
一个新的问题，在使用木斧子和石斧子出现的

### ISSUE THREAD

**Issue by BingZi-233** [SourceWriters/SmoothTimber#6] opened 2020-04-23 16:35 UTC
![J0kmK1.png](https://s1.ax1x.com/2020/04/24/J0kmK1.png)

**Comment by Lauriichen** [comment] 2020-04-23 17:37
So what did you do to achieve this?

**Comment by Lauriichen** [comment] 2020-04-23 17:53
okay so, smoothtimber is tracking blocks asynchronous and the problem is that it's trying to track a block in a chunk that is not generated yet.

**Comment by Lauriichen** [comment] 2020-04-23 17:55
Okay should be fixed in pre-1.6.5

**Closed by Lauriichen** 2020-04-23 17:55 UTC
