### ISSUE TITLE
[BUG]: Unbreakable axes disappear after usage

### ISSUE THREAD

**Issue by Glionox** [SourceWriters/SmoothTimber#55] opened 2023-01-04 03:13 UTC
### Describe what happend

Axes with unbreakable tag disappear after N uses equal to their durability.
Stone axe disappear after 131 broken blocks, iron after 250 blocks, etc.

### Reproduction steps

1. Obtain unbreakable axe (give @s stone_axe{Unbreakable:1b} 1).
2. Plant or find large trees like jungle or spruce.
3. Cut down trees.

### Expected behavior

An unbreakable axe doesn't disappear after any number of broken blocks.

### Java Version

Java 17

### Server Software

Paper

### Minecraft Version

1.19.1

### Plugin Version

1.22.5

**Comment by Lauriichan** [comment] 2023-01-04 08:58
Duplicate of #16

**Closed as completed by Lauriichan** 2023-01-04 08:58 UTC
Labels: Bug, Duplicate
