### ISSUE TITLE
[HELP]: Console Spam Error

### ISSUE THREAD

**Issue by AlinMihai96** [SourceWriters/SmoothTimber#51] opened 2022-11-13 16:55 UTC
### With what do you need help?

My console is spamming this message
SmoothTimber || Detected a Jobs setting change, reloading Jobs settings...
How i can fix it?

### Java Version

Java 17

### Server Software

Paper

### Minecraft Version

1.18.2

**Comment by Lauriichan** [comment] 2022-11-13 16:56
duplicate of discord question

**Closed as completed by Lauriichan** 2022-11-13 16:56 UTC
Labels: Help, Invalid
